### ISSUE TITLE
A comment is removed after `pub` keyword in a struct.

### ISSUE THREAD

**Issue by xfix** [rust-lang/rustfmt#2781]
After reading http://journal.stuffwithstuff.com/2015/09/08/the-hardest-program-ive-ever-written/, I decided to put one of code examples provided here in Rust.

```rust
pub // Oh, crap. A line comment.
struct Foo {}
```

The original code used `abstract`, but there is no such keyword in Rust, I used `pub` instead. Rustfmt seeing that removed a comment. This is an edge case, I don't care what it formats down to, but I think comment should be preserved.

**Comment by anthonyclays** [comment]
This happens in a very large number of 'uncommon places for comments': http://play.rust-lang.org/?gist=f0e8521555680aed289378e1d8a7d849&version=stable&mode=debug

It'd be nice to at least print a warning when comments get thrown away. Ideally (IMO), rustfmt should move the comment to the first 'logical' place for comments strictly before its original location (but that's debatable: should these comments be moved before or after doc comments / atributes in the case of type / fn definitions?)

**Comment by zacheryph** [comment]
Another example. Comment in _the middle_ of struct/impl declaration. 

### Input File
```rust
struct X<T>
// where
//     T: Clone
{
    inner: String,
}
```

### After rustfmt
```rust
struct X<T> {
    inner: String,
}
```

**Comment by hsandt** [comment]
Exactly. This was noted in https://github.com/rust-lang/rustfmt/pull/1911 and fixed for [`impl`](https://github.com/rust-lang/rustfmt/pull/1925/commits/fa7c4d503015638a9696a54432beca7af6999f10) and [`trait`](https://github.com/rust-lang/rustfmt/pull/1925/commits/c4c55285daf803750ec21ecdb77b6a04eb464566) only in https://github.com/rust-lang/rustfmt/pull/1925

We can assume the fix for struct would be similar as the cause should be similar, but not sure. I've noticed in particular that a comment just before a non-commented is not removed, as if protected. But I don't have an old rustfmt right now to check if this was also the case for `impl` and `trait`.

```
struct X<T>
// this will remain
where
    T: Clone
{
    inner: T
}
```

Should we split this issue in 2? (one for the `pub` part, one for the part before the brace)

I think a developer solving one issue will solve the other in the surrounding code at the same time, but I can't confirm until we find the exact cause.

Inspired by the fix for `impl` and `trait`, I searched for `find_uncommented("{")` and `find_uncommented("where")` in `rustfmt/src/items.rs` and found some occurrences, but not inside [format_struct_struct](https://github.com/topecongiro/rustfmt/blob/fa7c4d503015638a9696a54432beca7af6999f10/src/items.rs#L1018) itself.

Anyway, when solving this issue we should add comments at uncommon places in the unit tests to make sure they are preserved.

**Comment by scampi** [comment]
the problem in https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-405924561 is fixed in #3495

**Comment by hellow554** [comment]
The rest isn't fixed.

Another example:

```
pub fn a(_: &/* foo */()) {}
```

becomes

```
pub fn a(_: &()) {}
```

@topecongiro any reason why this (kind of critical) bug hasn't been fixed yet? It's almost open for a year now.

**Comment by scampi** [comment]
@hellow554 Thanks for giving an additional example where the comment is lost. That seems a strange place to put a comment though.
You are welcome to propose a PR to help resolve this issue faster too ;o)

**Comment by scampi** [comment]
Maybe we could try to create some kind of code generator that inserts comments at random places and see where comments are lost. The reason is that the span between some token is not taken into consideration and therefore you get lost comments. But I feel like that would make the code base harder to maintain. Or a re-design would be needed to facilitate how these missing spans are retained, at the moment it creeps in every `rewrite` method and the missing span needs to be carefully handled...

**Comment by paulstansifer** [comment]
I think I found another example (https://github.com/paulstansifer/unseemly/pull/17/files#diff-7328e869d09a114ad85e6ac59329ae4fL45)

```rust
    type Err : Debug /*Display*/ + Reifiable + Clone;
```
...goes to:
```rust
    type Err: Debug + Reifiable + Clone;
```

...I agree that I probably should not have put a comment there, though

**Comment by 0xd34d10cc** [comment]
Yet another example:

```rust
use std::collections::{
  HashMap,
  // hash_map::Entry  
};
```

**Comment by pnkfelix** [comment]
Yet another example: 

```rust
pub type Export /*: Bound */ = S1;
```

This is one where I think a comment *is* justified; today we do not enforce such bounds (i.e. the compiler does not check that the right-hand side of a `type` definition actually conforms to such a bound), and the compiler actually errors if you try to include it (because we don't want people to mistakenly think that such bounds are enforced).

But the comment here serves a useful purpose (about the *intent*, that we intend for this type definition to conform to the bound).

**Comment by hellow554** [comment]
@ayazhafiz I see, that you opened a seperate issue for the other problems, but I can't find that you covered [my problem](https://github.com/rust-lang/rustfmt/issues/2781#issuecomment-496403822) and it's still not fixed. Am I missing something?

**Comment by ayazhafiz** [comment]
@hellow554 sorry about that, added back in  #4245
