### ISSUE TITLE
Style guide does not match rustfmt formatting for long-but-not-super-long trait bounds

### ISSUE THREAD

**Issue by daboross** [rust-lang/rustfmt#3047]
Traits with very few bounds get formatted correctly:

```rust
pub trait SpawnPrioritization: Ord + Copy + Clone + Azdef + Bzdef + Czdef + Dzdef + Ezdef {}
```

Traits with many bounds also do:

```rust
pub trait SpawnPrioritization:
    Ord
    + Copy
    + Clone
    + Azdef
    + Bzdef
    + Czdef
    + Dzdef
    + Ezdef
    + Fzdef
    + Gzdef
    + Hzdef
    + Izdef
    + Jzdef
    + Lzdef
{
}
```

However, if there's a trait with enough bounds that it just doesn't fit on the main line but doesn't trigger the overflow, rustfmt will format it like this:

```rust
pub trait SpawnPrioritization:
    Ord + Copy + Clone + Azdef + Bzdef + Czdef + Dzdef + Ezdef + Fzdef + Gzdef + Hzdef + Izdef
{
}
```

This style is not listed in https://github.com/rust-lang-nursery/fmt-rfcs/blob/070ed1396d2ad4eda919bf08a797446b957d3ca1/guide/items.md#traits.

Would it be possible to either remove this, or mention it in `fmt-rfcs`? I'd prefer removal, but either would solve this.

Using `rustfmt 0.99.4-nightly (1c40881 2018-08-27)`.

**Comment by nrc** [comment]
I think this is expected behaviour - we are splitting the signtaure at `:`, and in that case there is no need to split the bounds. We should fix the style guide.

**Comment by daboross** [comment]
It looks like the style guide still doesn't mention this: https://github.com/rust-dev-tools/fmt-rfcs/blob/7416e12356a55aae959e9629b58eb7c7c3c86f6f/guide/items.md#traits, and rustfmt built from the latest master (`a441d5e2`) still has the behavior described in the OP.

Am I mistaken, or is there another reason for closing this?

**Comment by calebcartwright** [comment]
> Should I make a new issue on the fmt-rfcs repo

Yup. Seems like a PR to call this case out explicitly in the style guide would be the next step. Believe this was closed because the action should be taken in the fmt-rfcs repo and there's no additional action to be taken here.
