### ISSUE TITLE
Formatting produces code that triggers internal error

### ISSUE THREAD

**Issue by theduke** [rust-lang/rustfmt#3658]
I've run into a situation where applying formatting produces code with trailing whitespace, resulting in a "Internal error: left behind trailing whitespace" error on the next invokation.

Tested on stable and yesterdays nightly.

```rust
pub type ResponseHandler = Box<
    Fn(
            protocol::network::events::ResponseReceivedEventParams,
            &dyn Fn() -> Result<
                protocol::network::methods::GetResponseBodyReturnObject,
                failure::Error,
            >,
        ) + Send
        + Sync,
>;
```

This gets formatted to 

```rust
pub type ResponseHandler = Box<
    Fn(
            protocol::network::events::ResponseReceivedEventParams,
            &dyn Fn(
                     // <<< Trailing WS here!
            ) -> Result<
                protocol::network::methods::GetResponseBodyReturnObject,
                failure::Error,
            >,
        ) + Send
        + Sync,
>;
```

**Comment by rchaser53** [comment]
This has already been fixed in #3653.

**Comment by theduke** [comment]
Is that fix supposed to be in the latest nightly yet?

It's still failing for me with `rustc 1.37.0-nightly (8ebd67e4e 2019-06-27)`.

**Comment by topecongiro** [comment]
Closing as a duplicate of #3651.

@theduke I will release 1.3.1 this weekend, and it should be available via rustup in a few days.
