### ISSUE TITLE
"left behind trailing whitespace" when breaking after visibility of a field

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rustfmt#5703]
```
$ rustup run nightly cargo fmt -- --check
Diff in /home/jplatte/code/matrix-rust-sdk/crates/matrix-sdk/src/room/timeline/event_item/content.rs at line 292:
 /// of the sender of the reaction.
 #[derive(Clone, Debug, Default)]
 pub struct ReactionGroup(
-    pub(in crate::room::timeline)
+    pub(in crate::room::timeline) 
         IndexMap<(Option<OwnedTransactionId>, Option<OwnedEventId>), OwnedUserId>,
 );
 
error[internal]: left behind trailing whitespace
   --> /home/jplatte/code/matrix-rust-sdk/crates/matrix-sdk/src/room/timeline/event_item/content.rs:295:295:34
    |
295 |     pub(in crate::room::timeline) 
    |                                  ^
    |
```

**Comment by ytmimi** [comment]
@jplatte thanks for reaching out. Can you post the original code snippet instead of the diff. Additionally, what version of rustfmt are you using and are you using any non default configuration options?

**Comment by jplatte** [comment]
This is from https://github.com/matrix-org/matrix-rust-sdk/pull/1599 before pulling out the inner type of `ReactionGroup` in `crates/matrix-sdk/src/room/timeline/event_item/content.rs` into a type alias. The version of rustfmt that produces this error is `1.5.2-nightly (7281249 2023-02-27)`. Does that answer your questions?

**Comment by ytmimi** [comment]
Yeah, that helps! I just want to be clear that this was the original input snippet, and that there was no trailing whitespace to begin with.

```rust
#[derive(Clone, Debug, Default)]
pub struct ReactionGroup(
    pub(in crate::room::timeline) 
        IndexMap<(Option<OwnedTransactionId>, Option<OwnedEventId>), OwnedUserId>,
);
```

**Comment by shulaoda** [comment]
Unable to reproduce this issue, it may have been fixed.

**Comment by ytmimi** [comment]
I can still reproduce this with rustfmt 1.8.0-nightly (292865f8d3 2025-10-09)

**Comment by shulaoda** [comment]
> I can still reproduce this with rustfmt 1.8.0-nightly ([292865f](https://github.com/rust-lang/rustfmt/commit/292865f8d34ea42f4a18a22906bb9f4bc1d15ee9) 2025-10-09)

Thank you for pointing that out. I’ve tried again and can now reproduce the issue, I’m not sure why it didn’t occur before.
